### ISSUE TITLE
NuGet vs Choco package version mismatch

### ISSUE THREAD

**Issue by rcmaehl** [crazy-max/ghaction-chocolatey#156]
#### Steps to reproduce this issue

1. Pack Software
2. Push Software

#### Expected behaviour

Software packed succesfully

#### Actual behaviour

> Despite version being 0.7.4.0, package gets packed as 0.7.4 causing a file not found error later in the process

### Configuration

* Repository URL (if public): https://github.com/rcmaehl/MSEdgeRedirect
* Build URL (if public): 

```yml
name: Chocolatey Deploy

on:
  release:
    types: [published]
  workflow_dispatch:

defaults:
  run:
    shell: bash

jobs:
  chocolatey:
    name: Deploy
    runs-on: windows-latest
    if: github.repository == 'rcmaehl/MSEdgeRedirect'
    steps:
      - name: Clone Repository
        uses: actions/checkout@v3
      - uses: oprypin/find-latest-tag@v1
        with:
          repository: rcmaehl/MSEdgeRedirect  # The repository to scan.
          releases-only: true  # We know that all relevant tags have a GitHub release for them.
        id: latesttag
      - name: Set Checksum
        run: |
          filename="MSEdgeRedirect.exe"
          url="https://github.com/${{ github.repository }}/releases/download/${{ steps.latesttag.outputs.tag }}/${filename}"
          sed -i "s#{URL64}#${url}#g" "Assets/Choco/MSEdgeRedirect/tools/chocolateyinstall.ps1"
          curl -sSL "${url}" -o "Assets/Choco/${filename}"
          sha256=$(cat "Assets/Choco/${filename}" | sha256sum -)
          sed -i "s/{SHA256CHECKSUM64}/${sha256:0:64}/g" "Assets/Choco/MSEdgeRedirect/tools/chocolateyinstall.ps1"
      - name: Set Version
        id: version
        run: |
          version=${{ steps.latesttag.outputs.tag }}
          echo "::set-output name=nuget::$version"
          sed -i "s/{VERSION}/${version}/g" "Assets/Choco/MSEdgeRedirect/msedgeredirect.nuspec"
      - name: Pack Release
        uses: crazy-max/ghaction-chocolatey@v2.2.0
        with:
          args: pack Assets/Choco/MSEdgeRedirect/msedgeredirect.nuspec --outputdirectory Assets/Choco/MSEdgeRedirect
      - name: Upload Release
        uses: crazy-max/ghaction-chocolatey@v2.2.0
        with:
          args: push Assets/Choco/MSEdgeRedirect/msedgeredirect.${{ steps.version.outputs.nuget }}.nupkg -s https://push.chocolatey.org/ -k ${{ secrets.CHOCO_KEY }}
```

### Logs

[logs_760.zip](https://github.com/crazy-max/ghaction-chocolatey/files/11896554/logs_760.zip)
