### ISSUE TITLE
Could not find part of the path 'wksp/tools'

### ISSUE THREAD

**Issue by jhotmann** [crazy-max/ghaction-chocolatey#75]
### Behaviour
Attempting to automatically create a chocolatey package of my command line tool using GitHub Actions.

#### Expected behaviour

> pack command should create .nupkg file

#### Actual behaviour

> Get this error: `Could not find a part of the path '/wksp/tools'.`

### Configuration

* Repository URL (if public): https://github.com/jhotmann/node-rename-cli
* Build URL (if public): https://github.com/jhotmann/node-rename-cli/runs/657792210?check_suite_focus=true

```yml
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm ci
    - run: npm i -g pkg
    - run: npm run-script build --if-present
    - uses: actions/upload-artifact@v2
      with:
        name: binaries
        path: /home/runner/work/node-rename-cli/node-rename-cli/bin
    - run: npm run-script chocolatey --if-present
    - run: ls chocolatey/rename-cli/tools/
    - name: Choco package
      uses: crazy-max/ghaction-chocolatey@v1
      with:
        args: pack chocolatey/rename-cli/rename-cli.nuspec
```

### Logs

> Download the [log file of your build](https://help.github.com/en/actions/configuring-and-managing-workflows/managing-a-workflow-run#downloading-logs) and [attach it](https://help.github.com/en/github/managing-your-work-on-github/file-attachments-on-issues-and-pull-requests) to this issue.

[logs_25.zip](https://github.com/crazy-max/ghaction-chocolatey/files/4602005/logs_25.zip)
